language: c

env:
  global:
  - TEST_DIM=264x130
  - TEST_FRAMES=10

# Use container based infrastructure
sudo: false

# Use this the global requirements list for valgrind tests, because those are the most numerous.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - libtool
    - p7zip-full  # to uncompress our own ffmpeg binary
    - valgrind
    - yasm

matrix:
  fast_finish: true
  
  #allow_failures:
  #- os: osx  # Don't know what's wrong. Something changed in the environment.
  
  include:
    # We have some Mac specific code and Mac sometimes has odd build issues.
    - os: osx
      compiler: clang  # gcc is actually clang on Travis OS X
      osx_image: xcode8.2
    
    - os: osx
      compiler: clang  # gcc is actually clang on Travis OS X
      osx_image: xcode8.1
    
    - os: osx
      compiler: clang  # gcc is actually clang on Travis OS X
      osx_image: xcode8
    
    - os: osx
      compiler: clang  # gcc is actually clang on Travis OS X
      osx_image: xcode7.3
    
    - os: osx
      compiler: clang  # gcc is actually clang on Travis OS X
      osx_image: xcode6.4
    
    - os: osx



install:
  - source .travis-install.sh

script:
  - source .travis-script.sh
  
after_script:
  - set +e # Disable errors to work around Travis not knowing how to fix their stuff.
